// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Granary.Models.DataLayer;

#nullable disable

namespace Granary.Migrations
{
    [DbContext(typeof(GranaryContext))]
    partial class GranaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Granary.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Includes all tomato varieties like Roma, Cherry, and Beefsteak.",
                            Name = "Tomatoes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Covers common edible mushrooms such as White, Portobello, and Shiitake.",
                            Name = "Mushrooms"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Includes Yellow, Red, Sweet, and specialty onions like Cippolini.",
                            Name = "Onions"
                        });
                });

            modelBuilder.Entity("Granary.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            InvoiceDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 1
                        },
                        new
                        {
                            InvoiceId = 2,
                            InvoiceDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 2
                        },
                        new
                        {
                            InvoiceId = 3,
                            InvoiceDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 3
                        },
                        new
                        {
                            InvoiceId = 4,
                            InvoiceDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 4
                        },
                        new
                        {
                            InvoiceId = 5,
                            InvoiceDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("Granary.Models.InvoiceProduct", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            ProductId = 1,
                            Quantity = 25.0m
                        },
                        new
                        {
                            InvoiceId = 1,
                            ProductId = 2,
                            Quantity = 15.0m
                        },
                        new
                        {
                            InvoiceId = 2,
                            ProductId = 3,
                            Quantity = 40.0m
                        },
                        new
                        {
                            InvoiceId = 2,
                            ProductId = 4,
                            Quantity = 20.0m
                        },
                        new
                        {
                            InvoiceId = 3,
                            ProductId = 5,
                            Quantity = 10.0m
                        },
                        new
                        {
                            InvoiceId = 3,
                            ProductId = 6,
                            Quantity = 12.0m
                        },
                        new
                        {
                            InvoiceId = 4,
                            ProductId = 2,
                            Quantity = 18.0m
                        },
                        new
                        {
                            InvoiceId = 4,
                            ProductId = 3,
                            Quantity = 22.0m
                        },
                        new
                        {
                            InvoiceId = 5,
                            ProductId = 7,
                            Quantity = 50.0m
                        },
                        new
                        {
                            InvoiceId = 5,
                            ProductId = 8,
                            Quantity = 30.0m
                        });
                });

            modelBuilder.Entity("Granary.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Small sweet tomatoes",
                            Name = "Cherry Tomatoes",
                            StockQuantity = 100m,
                            UnitPrice = 2.99m,
                            UnitType = "each"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Ideal for sauces",
                            Name = "Roma Tomatoes",
                            StockQuantity = 200m,
                            UnitPrice = 1.49m,
                            UnitType = "pound"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Large slicing tomato",
                            Name = "Beefsteak Tomatoes",
                            StockQuantity = 150m,
                            UnitPrice = 1.25m,
                            UnitType = "each"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Mild and versatile",
                            Name = "White Mushrooms",
                            StockQuantity = 80m,
                            UnitPrice = 3.25m,
                            UnitType = "pound"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Meaty texture, great grilled",
                            Name = "Portobello Mushrooms",
                            StockQuantity = 60m,
                            UnitPrice = 1.99m,
                            UnitType = "each"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Savory and rich flavor",
                            Name = "Shiitake Mushrooms",
                            StockQuantity = 300m,
                            UnitPrice = 0.75m,
                            UnitType = "ounce"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Common all-purpose onion",
                            Name = "Yellow Onions",
                            StockQuantity = 500m,
                            UnitPrice = 0.89m,
                            UnitType = "pound"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Colorful and sharp",
                            Name = "Red Onions",
                            StockQuantity = 400m,
                            UnitPrice = 1.10m,
                            UnitType = "pound"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Mild and sweet",
                            Name = "Sweet Onions",
                            StockQuantity = 350m,
                            UnitPrice = 1.30m,
                            UnitType = "pound"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Small and sweet, ideal for roasting",
                            Name = "Cippolini Onions",
                            StockQuantity = 250m,
                            UnitPrice = 0.60m,
                            UnitType = "each"
                        });
                });

            modelBuilder.Entity("Granary.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Description = "A warm and savory soup made from fresh tomatoes and onions.",
                            Name = "Tomato Soup"
                        },
                        new
                        {
                            RecipeId = 2,
                            Description = "Mushroom caps filled with a savory onion and herb blend.",
                            Name = "Stuffed Mushrooms"
                        },
                        new
                        {
                            RecipeId = 3,
                            Description = "A classic Italian-style tomato and mushroom sauce.",
                            Name = "Marinara Sauce"
                        },
                        new
                        {
                            RecipeId = 4,
                            Description = "A fresh salad combining red and yellow onions with cherry tomatoes.",
                            Name = "Onion Salad"
                        });
                });

            modelBuilder.Entity("Granary.Models.RecipeProduct", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("RecipeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            ProductId = 1,
                            Quantity = 4.0m
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 7,
                            Quantity = 1.0m
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 4,
                            Quantity = 6.0m
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 8,
                            Quantity = 0.5m
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 2,
                            Quantity = 3.0m
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 5,
                            Quantity = 2.0m
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 7,
                            Quantity = 1.0m
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 8,
                            Quantity = 1.0m
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 1,
                            Quantity = 1.0m
                        });
                });

            modelBuilder.Entity("Granary.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            SupplierName = "Fresh Farms Co."
                        },
                        new
                        {
                            SupplierId = 2,
                            SupplierName = "Harvest Supply Ltd."
                        },
                        new
                        {
                            SupplierId = 3,
                            SupplierName = "Mushroom Masters"
                        },
                        new
                        {
                            SupplierId = 4,
                            SupplierName = "Tomato Town Inc."
                        },
                        new
                        {
                            SupplierId = 5,
                            SupplierName = "Onion Bros."
                        });
                });

            modelBuilder.Entity("Granary.Models.SupplierProduct", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("SupplierId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupplierProducts");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            SupplierId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            SupplierId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            SupplierId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            SupplierId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            SupplierId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            SupplierId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            SupplierId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            SupplierId = 5,
                            ProductId = 7
                        },
                        new
                        {
                            SupplierId = 5,
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("Granary.Models.Invoice", b =>
                {
                    b.HasOne("Granary.Models.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Granary.Models.InvoiceProduct", b =>
                {
                    b.HasOne("Granary.Models.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Granary.Models.Product", "Product")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Granary.Models.Product", b =>
                {
                    b.HasOne("Granary.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Granary.Models.RecipeProduct", b =>
                {
                    b.HasOne("Granary.Models.Product", "Product")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Granary.Models.Recipe", "Recipe")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Granary.Models.SupplierProduct", b =>
                {
                    b.HasOne("Granary.Models.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Granary.Models.Supplier", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Granary.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Granary.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceProducts");
                });

            modelBuilder.Entity("Granary.Models.Product", b =>
                {
                    b.Navigation("InvoiceProducts");

                    b.Navigation("RecipeProducts");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("Granary.Models.Recipe", b =>
                {
                    b.Navigation("RecipeProducts");
                });

            modelBuilder.Entity("Granary.Models.Supplier", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("SupplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
